# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-07 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='retail',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='wholesale',
            field=models.IntegerField(default=0),
        ),
    ]
