# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-07 23:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20170507_1304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='retail',
        ),
        migrations.RemoveField(
            model_name='product',
            name='wholesale',
        ),
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default='test', max_length=200),
        ),
    ]
