# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-09 11:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_product_quantity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
    ]
