# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-10 23:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20170509_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pid',
            field=models.CharField(default='111111111', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
